site_name: 文心一言 ERNIE Bot SDK
theme:
  name: material
  custom_dir: ./.overrides
  features:
    - content.code.copy
  logo: assets/images/favicon.png
  repo_url: https://github.com/PaddlePaddle/ERNIE-Bot-sdk
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  language: zh
  palette:
    primary: white
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 使用文档:
    - 预备步骤:
      - README.md
      - installation.md
      - authentication.md
      - configuration.md
      - models.md
    - 使用指南:
      - guides/chat_completion.md
      - guides/embedding.md
      - guides/image.md
      - guides/function_calling.md
  - API文档:
    - api_reference/chat_completion.md
    - api_reference/embedding.md
    - api_reference/image.md
