name: AgentLint

on:
  push:
    paths:
      - .github/workflows/agent_*.yaml
      - erniebot-agent/**
  pull_request:
    paths:
      - .github/workflows/agent_*.yaml
      - erniebot-agent/**

jobs:
  AgentLint:
    name: Agent Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip # Caching pip dependencies
          cache-dependency-path: |
            erniebot-agent/setup.cfg
            erniebot-agent/tests/requirements.txt
      - name: Install erniebot-agent and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e erniebot-agent[all]
          python -m pip install -r erniebot-agent/tests/requirements.txt
      - name: Run the script
        run: python scripts/run_erniebot_agent_checks.py
